---
title: "Week 09"
subtitle: "Working with strings"
output: 
  prettydoc::html_pretty:
    theme: hpstr
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Statistician of the Week

[Maria Cuellar](https://crim.sas.upenn.edu/people/maria-cuellar)

[Abby Smith](https://www.linkedin.com/in/abby-smith-55312a200/)

### Announcements

+ Today: AE-06, maybe start Lab 08

+ Thursday's quiz will use 4 previous quizzes as a question bank; you'll see questions of the same exact format but with different data/output

+ Looking ahead: next project due date is the "Preliminary data story" due Tuesday before Easter (March 31)
    + Next week changed to be project work week. 
    + Next Tuesday will spend time producing a bunch of visualizations & tables (send 10 to me by Thursday morning). 
    + Next Thursday will be spent as a "storyboarding" session


    
<!-- No class Thursday -->

<!-- Project Data Cleaning & EDA due Thursday  -->

<!-- + Make sure to turn in .zip folder with all appropriate files -->

<!-- Annotations due Saturday (in case you want extra time to focus on project) -->

<!-- Next week: Inference for Numerical Data -->

<!-- + 3 videos, 51 mins total -->

<!-- Today: AE-07 / Lab 07  -->

<!-- + Points wise counts as 2 AEs (20 points instead of 10) but will be graded for correctness (not just completion) -->

<!-- + Due Tuesday by class-time, like a lab -->

### Feedback from mid-semester survey

+ Two-thirds say pacing is about right (1/3 a little fast)

+ 80% say difficulty is about right (1 a little too easy, 1 a little too hard)

+ 55% say workload is about right, 45% say a little heavy

    + Some qualitative comments mention workload feeling a litle heavy, labs being a little long

+ My goal for your time (6hrs outside class for 3 credit class): 
    + <1hr prep for Tuesdays
    + 1hr on reading annotations
    + <1hr preparing for quiz
    + 1-3hrs finishing lab or project assignment
    
+ Will be mindful of lab lengths moving forward! Some weeks we'll combine AE & Lab, so you'll have more time for projects in class. 

+ Suggested posting solutions to AEs - I can start doing that! 

+ A lot of nuances come up in AEs/labs that aren't covered in lecture notes - this is intentional :)

+ More live coding (by me) in class - I can do that! 

+ Some people love the flipped design, other mixed

+ Data ethics seems to be an appreciated component of the course

### What's left 

In the final 7 weeks (including this week):
    
  + 13 class periods, 8 of which will be project-oriented
  + 3 labs
  + 2 AEs
  + 3 quizzes
  + 2 annotations

### Application Exercise

-   The remainder of class will be spent on AE-06.
- You can access it from GitHub. 
- It is due at the end of class today. 
-   To turn it in, you should upload your .html file to Blackboard.
