---
title: "Week 11"
subtitle: "Project Storyboarding"
output: 
  prettydoc::html_pretty:
    theme: hpstr
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Statisticians of the Week

[Beth Tipton](https://www.ipr.northwestern.edu/news/2019/faculty-spotlight-beth-tipton.html)

[Larry Hedges](https://www.ipr.northwestern.edu/who-we-are/faculty-experts/hedges.html)

### Upcoming schedule

| Week | Tue in-class | Thur in-class |
|-----------|----------------|---------------|
| Week 11 (Mar 31) | Quiz 06 + Storyboarding | NO CLASS – Easter |
| Week 12 (April 7, 9) | Web scraping (Lab 09) | Project work session |
| Week 13 (April 14, 16) | Communicating results (Lab 10) | Quiz 07 + Project work session |
| Week 14 (April 21, 23) | Peer review (presentations) | Peer review (written reports) |
| Week 15 (April 28, 30) | Presentations | Presentations |

# Why storyboarding?

+ Communication is perhaps one the most important skills w/in data science (especially within the age of AI)
+ Want to avoid "I did this, then I did this, then I did this..."
+ CURSE OF EXPERTISE! 

# Some reminders before getting started

+ This is a PRELIMINARY data story - you will continue to add to it / change after today
+ Keep brainstorming throughout about other visualizations that can contribute to your story
+ Identifying a story doesn't mean ignoring all contradictory evidence
+ It's okay for there to be competing stories - your job is to weave them together / discuss / contrast them in compelling ways

[The process/deliverables](https://villanova-my.sharepoint.com/:w:/g/personal/kfitzg24_villanova_edu/IQBgTiatD6GJQZmW8nOajHPfAf8hfuF7U-dk7I1uy8gfC5E)