---
title: "Week 14"
subtitle: "Project Peer Review"
output: 
  prettydoc::html_pretty:
    theme: hpstr
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Thursday Announcements

- Take a look at [project evaluation rubric](https://villanova-my.sharepoint.com/:x:/r/personal/kfitzg24_villanova_edu/Documents/Desktop/Nova/STAT%204380/STAT%204380%20S26%20Projects/Written%20Report%20Rough%20Drafts/Project%20evaluation%20rubric.xlsx?d=w859bb67eaccc4263925fa060d71926f5&csf=1&web=1&e=lDHdBw) (also located in shared OneDrive folder. 
    + Make sure you can [Render to pdf](https://quarto.org/docs/output-formats/pdf-basics.html)! 
    + Make sure your report is FULLY reproducible - including file paths! 
+ Take 5 minutes in your group to create a to-do list 

### Peer Review of Rough Drafts

In your groups,

+ Start by discussing initial impressions
+ Read through Written Report section of [Project Evaluation Rubric](https://villanova-my.sharepoint.com/:x:/r/personal/kfitzg24_villanova_edu/Documents/Desktop/Nova/STAT%204380/STAT%204380%20S26%20Projects/Written%20Report%20Rough%20Drafts/Project%20evaluation%20rubric.xlsx?d=w859bb67eaccc4263925fa060d71926f5&csf=1&web=1&e=wFcnTe)
+ In the shared OneDrive folder, create a COPY of the Rough draft peer review feedback TEMPLATE and fill it out in your groups
+ Begin your formal write-up
    

Your formal peer-review write-up should be 1-2 pages and include:

+ A summary of the research questions, data context, and findings, as you understand them
+ Brief comments on strengths of the paper
+ Constructive criticism, raising questions / points of confusion, and outlining what needs to be changed/improved in order for the report to be exemplary

The constructive criticism should make up the bulk of the review. Remember: the goal is to help them IMPROVE the work. You should NOT simply tell them it’s wonderful, and you should NOT simply criticize without offering concrete suggestions for HOW to improve. Your write-up should be a focused synthesis, not simply a item-by-item rehashing of the feedback spreadsheet.  

### Tuesday Announcements

- Quiz to start class today (last one!)
- Student hours on Thursday will be 1:15 - 2:15
- End of Course Reflection(\~1 page), due next Thursday
    + Meta-cognition important for learning
    + More nitty gritty feedback / course-specific suggestions for how to improve
    + Concrete things changed based on previous years' feedback:
      -   No HW assignments (reduced work-load)
      -   No Posit Cloud (web-based version of RStudio)
      -   In-class group work but individual submissions 
      -   Shorter lecture videos
- Today: Peer review of slides
- Thursday: Peer review of written reports
- BEFORE Thursday: Read the written report assigned to you - jot down initial (informal) impressions / suggestions as you go. The hard copy is for YOU to mark up - you will not be giving your written notes to the group. 
+ Sat April 25 (11:59pm): Formal peer review submitted
+ Tue & Th April 28 & 30: Presentations - must be in class both days!
+ A note on presentations: not every group member needs to present! Play to your strengths.
+ Monday May 4: Final deliverables (report + repository)

## Why peer review?

+ Feedback makes us better - we should never assume our perspective / work is ultimate
+ Curse of expertise
+ Giving good feedback is a skill (which requires practice)
+ Asking for, receiving, and incorporating feedback is a skill (which requires practice)
+ It's a part of professional life
+ Assessing others' work helps you self-assess and improve your own work
+ Has potential to help your grade! Give the constructive feedback now, before I take points off for it later :) 


**Your task: help them make their project better!** It is NOT helpful or sufficient to say it all looks great. **Don't just critique - give specific suggestions!**

+ ~10 minutes - read over rubric & slides on your own, start taking notes for yourself
+ ~10 minutes - Discuss initial impressions in your groups
    + What do you all think was the main takeaway?
    + Where were people confused? (same spots?)
    + What visualizations came up repeatedly as unclear?
+ ~15 minutes - Fill out feedback form together
+ ~10 minutes - Identify 2-3 specific changes you will make to your own slides
+ ~10 minutes - Debrief

## Group assignments (for slides only):

+ Nixie & Mae review Jay & Ryan
+ Jay & Ryan review Will & Zach
+ Will & Zach review Catherine, Deanna, Perry
+ Catherine, Deanna, Perry review Alex & Andrew
+ Alex & Andrew review Claire & Sophie
+ Claire & Sophie review Hannah & Briell
+ Hannah & Briell review Nixie & Mae
