---
title: "Statistics Experiences"
output: 
  tufte::tufte_html:
    css: ./hw.css
    tufte_variant: "envisioned"
    highlight: pygments
link-citations: yes
---

```{r include = FALSE}
knitr::opts_chunk$set(
  eval = FALSE,
  out.width = "80%",
  fig.asp = 0.618,
  fig.width = 6
)
```

+ **Statistics Experience 01 due September 21, 11:59pm**
+ **Statistics Experience 02 due November 16, 11:59pm**

The world of statistics and data science is vast and dynamic! The goal of the statistics experience assignments is to help you engage with the statistics and data science communities outside of the classroom. There are a variety of ways you can participate in “Statistics Experiences,” which include but are not limited to listening to a podcast, reading a book, getting coffee with a statistician, joining the American Statistical Association, or participating in #TidyTuesday. Each experience is worth a varying number of points (see below for details), and you are required to collect at least 5 “Statistics Experience points” throughout the semester. Up to 10 additional points can be collected and added to your lowest homework grade(s).

Each experience has two parts:

`r emo::ji("one")` Have a statistics experience

`r emo::ji("two")` Post a one-paragraph reflection on Canvas

**You must complete both parts to receive credit.**


# Part 1: Experience statistics outside of the classroom 

The following are categories of possible statistics experiences, each worth a varying number of points. Suggested activities are included in each category. You  do not have to do one these suggested activities. You are welcome to find other activities as long as they are related to statistics/data science and they fit in one of the six categories. You can ask a question on the Canvas HELP Forum if there is an activity you'd like to do but you're not sure if it qualifies for the statistics experience.

## Category A: Engage with statistics in popular media

### Listen to a podcast or watch a video about statistics and data science (2pts)

The podcast or video must be **<u>at least 30 minutes</u>** to count towards the statistics experience. A few suggestions are below: 

- [Stats + Stories Podcast](https://statsandstories.net/)
- [Causal Inference Podcast](https://casualinfer.libsyn.com/)
- [FiveThirtyEight Model Talk](https://fivethirtyeight.com/tag/model-talk/)
- [rstudio::global 2021 talks](https://www.rstudio.com/resources/rstudioglobal-2021/)
- [rstudio::conf 2020 talks](https://www.rstudio.com/resources/rstudioconf-2020/)


This list is not exhaustive. You may listen to other podcasts or watch other statistics/data science videos not included on this list. Ask Dr. Fitz if you are unsure whether a particular podcast or video will count towards the statistics experience.

### Read a book (chapter) on statistics/data science (2pts/chapter)

There are *a lot* of books about statistics, data science, and related topics. A few suggestions are below. If you decide to read a book that isn't on this list, ask Dr. Fitz to make sure it counts toward the experience. Many of these books are available through the APU library or can be borrowed from Dr. Fitz. 

- *Invisible Women: Data bias in a world designed for men* by Caroline Criado Perez
- *Weapons of Math Destruction* by Cathy O'Neil
- *How Charts Lie: Getting Smarter about Visual Information* by Alberto Cairo
- *The Art of Statistics: How to learn from data* by David Spiegelhalter
- *The Lady Tasting Tea: How statistics revolutionized science in the twentieth century* by David Salsburg
- *Automating Inequality: How high-tech tools profile, police, and punish the poor* by Virginia Eubanks
- *Algorithms of Oppression: How search engines reinforce racism* by Safiya Umoja Noble
- *The Signal and the Noise: Why so many predictions fail - but some don't* by Nate Silver

You will earn 2 points for each chapter you submit a reflection on.

### Read a news article or blogpost (1pt)

Read a news article, blog post, or even (substantive) Twitter thread relevant to statistics or data science. Some relevant websites/organizations:

- [FiveThirtyEight](https://fivethirtyeight.com)
- [The Upshot](https://www.nytimes.com/section/upshot) at The New York Times 
- [Pew Research Center](https://www.pewresearch.org)
- List of relevant [Twitter accounts](https://docs.google.com/spreadsheets/d/1FLKxuZ5dRUFX8ml0-H9uGrsjai9lRJiD-dSOjfQFv0g/edit?usp=sharing) to follow/find articles

## Category B: Engage with professionals in the field

### Meet with a statistician/ data scientist (3pts)

Get coffee or a meal with someone who uses statistics or data science in their daily work and ask them about it! This could include a professor, professional in industry, graduate student, etc. Dr. Fitz counts, but is only worth 2 points :)

### Join the ASA (1pt)

The [American Statistical Association](https://www.amstat.org) (ASA) is the primary professional organization for statisticians and data scientists in the U.S., and you can become a [student member](https://www.amstat.org/membership/become-a-member/membership-options) for $25. Membership is a great way to gain (ongoing!) exposure to various ways that statistics & data science are used in the professional world. It comes with access to several statistics-related journals and magazines, young professional networking opportunities, job postings, etc.

Note for this category, a discussion post is not required, but you should email Dr. Fitz confirmation of your membership. 

## Category C: Do Data Science!

### TidyTuesday (3pts) 

You may participate in a TidyTuesday challenge. New data sets are announced on Monday afternoons. You can find more information about TidyTuesday and see the data in the [TidyTuesday GitHub repo](https://github.com/rfordatascience/tidytuesday). 

A few guidelines: 

- Create an R project for your TidyTuesday submission.
- Your project should include 
  - The Quarto file with all the code needed to reproduce your visualization. 
  - An image of your final visualization 
- The visualization should include features or customization that are beyond what we've done in class . 
- Include the image of your visualization in your discussion post.

### Participate in a data science competition or challenge (3-5pts)

Participate in a statistics or data science competition. You can participate individually or with a team. Information for recurring data challenges are linked below. *You must talk with Dr. Fitz before choosing this option.*

- [This is Statistics: Fall Data Challenge](https://thisisstatistics.org/falldatachallenge/) 
- [Undergraduate Statistics Project Competition](https://www.causeweb.org/usproc/) 

## Category D: Respond thoughtfully to a peer's discussion post (1pt)

Provide a one-paragraph response to a peer's discussion post, engaging thoughtfully with the ideas presented and posing at least one question.

Note, you can only earn 1 of your first 5 points from this category, however additional responses can contribute to the 10 extra credit points available. 

# Part 2: Summarize your experience

Write a one-paragraph reflection summarizing your experience. Post the reflection to the appropriate Discussion thread on Canvas. 

Make sure the following are included in your reflection:

- Name and brief description of the event/podcast/competition/etc.
- Citation or link to web page for event/competition/etc.

Creativity is encouraged!


## Submission 

You should complete at least two points worth of Statistics Experiences by September 23. All 5 points must be completed by November 16. You can continue collecting the extra credit points through December 9 (Saturday before finals).

